/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AirbnbRouteImport } from './routes/airbnb'
import { Route as CleaningServicesEncinoRouteImport } from './routes/cleaning-services-encino'
import { Route as CleaningServicesStudioCityRouteImport } from './routes/cleaning-services-studio-city'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HouseCleaningShermanOaksRouteImport } from './routes/house-cleaning-sherman-oaks'
import { Route as HouseCleaningVanNuysRouteImport } from './routes/house-cleaning-van-nuys'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AirbnbRoute = AirbnbRouteImport.update({
  id: '/airbnb',
  path: '/airbnb',
  getParentRoute: () => rootRouteImport,
} as any)
const CleaningServicesEncinoRoute = CleaningServicesEncinoRouteImport.update({
  id: '/cleaning-services-encino',
  path: '/cleaning-services-encino',
  getParentRoute: () => rootRouteImport,
} as any)
const CleaningServicesStudioCityRoute =
  CleaningServicesStudioCityRouteImport.update({
    id: '/cleaning-services-studio-city',
    path: '/cleaning-services-studio-city',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseCleaningShermanOaksRoute =
  HouseCleaningShermanOaksRouteImport.update({
    id: '/house-cleaning-sherman-oaks',
    path: '/house-cleaning-sherman-oaks',
    getParentRoute: () => rootRouteImport,
  } as any)
const HouseCleaningVanNuysRoute = HouseCleaningVanNuysRouteImport.update({
  id: '/house-cleaning-van-nuys',
  path: '/house-cleaning-van-nuys',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/airbnb': typeof AirbnbRoute
  '/cleaning-services-encino': typeof CleaningServicesEncinoRoute
  '/cleaning-services-studio-city': typeof CleaningServicesStudioCityRoute
  '/contact': typeof ContactRoute
  '/house-cleaning-sherman-oaks': typeof HouseCleaningShermanOaksRoute
  '/house-cleaning-van-nuys': typeof HouseCleaningVanNuysRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/airbnb': typeof AirbnbRoute
  '/cleaning-services-encino': typeof CleaningServicesEncinoRoute
  '/cleaning-services-studio-city': typeof CleaningServicesStudioCityRoute
  '/contact': typeof ContactRoute
  '/house-cleaning-sherman-oaks': typeof HouseCleaningShermanOaksRoute
  '/house-cleaning-van-nuys': typeof HouseCleaningVanNuysRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles': typeof ArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/airbnb': typeof AirbnbRoute
  '/cleaning-services-encino': typeof CleaningServicesEncinoRoute
  '/cleaning-services-studio-city': typeof CleaningServicesStudioCityRoute
  '/contact': typeof ContactRoute
  '/house-cleaning-sherman-oaks': typeof HouseCleaningShermanOaksRoute
  '/house-cleaning-van-nuys': typeof HouseCleaningVanNuysRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/airbnb'
    | '/cleaning-services-encino'
    | '/cleaning-services-studio-city'
    | '/contact'
    | '/house-cleaning-sherman-oaks'
    | '/house-cleaning-van-nuys'
    | '/quote'
    | '/services'
    | '/articles/$slug'
    | '/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/airbnb'
    | '/cleaning-services-encino'
    | '/cleaning-services-studio-city'
    | '/contact'
    | '/house-cleaning-sherman-oaks'
    | '/house-cleaning-van-nuys'
    | '/quote'
    | '/services'
    | '/articles/$slug'
    | '/articles'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/airbnb'
    | '/cleaning-services-encino'
    | '/cleaning-services-studio-city'
    | '/contact'
    | '/house-cleaning-sherman-oaks'
    | '/house-cleaning-van-nuys'
    | '/quote'
    | '/services'
    | '/articles/$slug'
    | '/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AirbnbRoute: typeof AirbnbRoute
  CleaningServicesEncinoRoute: typeof CleaningServicesEncinoRoute
  CleaningServicesStudioCityRoute: typeof CleaningServicesStudioCityRoute
  ContactRoute: typeof ContactRoute
  HouseCleaningShermanOaksRoute: typeof HouseCleaningShermanOaksRoute
  HouseCleaningVanNuysRoute: typeof HouseCleaningVanNuysRoute
  QuoteRoute: typeof QuoteRoute
  ServicesRoute: typeof ServicesRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airbnb': {
      id: '/airbnb'
      path: '/airbnb'
      fullPath: '/airbnb'
      preLoaderRoute: typeof AirbnbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaning-services-encino': {
      id: '/cleaning-services-encino'
      path: '/cleaning-services-encino'
      fullPath: '/cleaning-services-encino'
      preLoaderRoute: typeof CleaningServicesEncinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaning-services-studio-city': {
      id: '/cleaning-services-studio-city'
      path: '/cleaning-services-studio-city'
      fullPath: '/cleaning-services-studio-city'
      preLoaderRoute: typeof CleaningServicesStudioCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house-cleaning-sherman-oaks': {
      id: '/house-cleaning-sherman-oaks'
      path: '/house-cleaning-sherman-oaks'
      fullPath: '/house-cleaning-sherman-oaks'
      preLoaderRoute: typeof HouseCleaningShermanOaksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house-cleaning-van-nuys': {
      id: '/house-cleaning-van-nuys'
      path: '/house-cleaning-van-nuys'
      fullPath: '/house-cleaning-van-nuys'
      preLoaderRoute: typeof HouseCleaningVanNuysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AirbnbRoute: AirbnbRoute,
  CleaningServicesEncinoRoute: CleaningServicesEncinoRoute,
  CleaningServicesStudioCityRoute: CleaningServicesStudioCityRoute,
  ContactRoute: ContactRoute,
  HouseCleaningShermanOaksRoute: HouseCleaningShermanOaksRoute,
  HouseCleaningVanNuysRoute: HouseCleaningVanNuysRoute,
  QuoteRoute: QuoteRoute,
  ServicesRoute: ServicesRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
